server:
  port: 8080

spring:
  resources:
    static-locations: "classpath:/static/"
                                     
okta:
  oauth2:
    issuer: https://dev-199195.oktapreview.com/oauth2/default
    clientId: 0oawno6th1YfRhOma0h7
    clientSecret: H-M0iqwNpK53KROPvsAn2uldj2iT6vAGbV_sfdLj
    rolesClaim: groups
